### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bernardosulzbach** [bernardosulzbach/dungeon#49]
## Design
- [x] Create a `Command` class (to encapsulate the commands entered by the user).
- [ ] AchievementBuilder class.
- [ ] Load hints from resource files.
- [ ] Store aliases independently and let the player add and remove aliases.
- [ ] Tagging system for locations. So special behavior could be added by appending a String to a set.
- [ ] Tags for "N", "E", "S" and "W" (accessible by North, East, South and West, respectively).
- [ ] Implement a type for the possible commands, create an instance for every command and iterate through a list instead of using a big if-then-else chain.
## Features & Content
- [x] Hero must also be able to critically hit with his bare hands.
- [ ] 20 achievements.
- [ ] Rivers.
- [ ] Bridges.
- [ ] Maps (a `map` command that prints an ASCII map of the locations the player already visited).
- [ ] Creature will have an bloodAlcoholContent double variable (% by volume).
- [ ] AttackAlgorithms will account for insobriety.
- [ ] Pocket Watch and Wrist Watch instead of clock.
- [ ] Implement a third coordinate to Point (z).
- [ ] Implement dungeons (in z = -1).
- [ ] Implement healing during sleep.
## Changes
- [ ] Remove the leveling system.
- [ ] Make less-than-enough-for-a-full-bite heal less than enough-for-a-full-bite would.
